# Generated by Django 4.1.4 on 2023-04-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRcord',
            new_name='AccessRecord',
        ),
    ]
