# Generated by Django 4.1.4 on 2023-04-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_accessrcord_accessrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='email',
            field=models.EmailField(default='cricket@gmail.com', max_length=254),
        ),
    ]
